### ISSUE TITLE
kraken configuration file to define tentacles

### ISSUE THREAD

**Issue by loeffert** [foomo/kraken#14]
it would be helpful to predefine required tentancles in a configuration file which is parsed and interpreted while starting the kraken server.

the yaml configuration file should look like this:

``` yaml
address: 127.0.0.1:8888
tentacles:
  tentacle-name:
    bandwidth: 5
    retry: 10
  another-tentacle:
    bandwidth: 2
    retry: 10
```
